version: '2'
services:
  api:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todos
